languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Onurcan Ari"

[params]
dateFormat = "2 January 2006"

description = "just trying to figure things out like everyone else"

[params.author]
name = "Onurcan Ari"
image = "images/profile-photo.webp"
headline = "just trying to figure things out like everyone else"
bio = "Software Developer"
links = [
  { email = "mailto:arionurcan@gmail.com" },
  { linkedin = "https://linkedin.com/in/onurcanari/" },
  { github = "https://github.com/onurcanari/" },
]
