name: yazılar - onurcanari
description: okur, 
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://onurcanari.github.io'
google_analytics: 'UA-138626202-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://onurcanari.github.io'
author:         'onurcanari'
authorTwitter:  'onurcanari'

permalink:       /:year/:month/:categories/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
